services:
  - type: web
    name: codeops-backend
    env: node
    plan: free
    rootDir: backend       # Run commands inside backend folder
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
